package router

import (
	"encoding/json"
	"os"
	"strconv"
	"sync"
	"testing"
)

// ---------------------------------------------------------------------------
// Golden fixture: the primary correctness gate, generated by fqdn_slots.py
// --emit-golden and checked verbatim here so this port can never silently
// diverge from the Python reference.
// ---------------------------------------------------------------------------

type goldenSlotTable struct {
	Tokens     []string `json:"tokens"`
	Slots      []int    `json:"slots"`
	ModuloSafe bool     `json:"modulo_safe"`
}

type goldenSlotFixture struct {
	Crc16KnownAnswer struct {
		Input    string `json:"input"`
		Crc16    int    `json:"crc16"`
		Crc16Hex string `json:"crc16_hex"`
	} `json:"crc16_known_answer"`
	NumBuckets map[string]goldenSlotTable `json:"num_buckets"`
}

func loadGoldenSlotFixture(t *testing.T) goldenSlotFixture {
	t.Helper()
	raw, err := os.ReadFile("../testdata/slot_tokens_golden.json")
	if err != nil {
		t.Fatalf("reading golden fixture: %v", err)
	}
	var fixture goldenSlotFixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parsing golden fixture: %v", err)
	}
	return fixture
}

func TestCrc16(t *testing.T) {
	fixture := loadGoldenSlotFixture(t)
	got := Crc16([]byte(fixture.Crc16KnownAnswer.Input))
	if int(got) != fixture.Crc16KnownAnswer.Crc16 {
		t.Fatalf("Crc16(%q) = 0x%04X, want 0x%04X (%s)",
			fixture.Crc16KnownAnswer.Input, got, fixture.Crc16KnownAnswer.Crc16, fixture.Crc16KnownAnswer.Crc16Hex)
	}
	if got != 0x31C3 {
		t.Fatalf("Crc16(%q) = 0x%04X, want 0x31C3", fixture.Crc16KnownAnswer.Input, got)
	}
}

func TestBucketTableMatchesGoldenFixture(t *testing.T) {
	fixture := loadGoldenSlotFixture(t)
	// Iterate the keys present in the file, not a hardcoded list, so a
	// regenerated fixture with more entries stays fully checked.
	for key, want := range fixture.NumBuckets {
		numBuckets, err := strconv.Atoi(key)
		if err != nil {
			t.Fatalf("golden fixture has non-integer num_buckets key %q", key)
		}
		t.Run(key, func(t *testing.T) {
			table, err := ComputeBucketTable(numBuckets)
			if err != nil {
				t.Fatalf("ComputeBucketTable(%d): %v", numBuckets, err)
			}
			if len(table.tokens) != len(want.Tokens) {
				t.Fatalf("tokens length = %d, want %d", len(table.tokens), len(want.Tokens))
			}
			for i := range want.Tokens {
				if table.tokens[i] != want.Tokens[i] {
					t.Errorf("tokens[%d] = %q, want %q", i, table.tokens[i], want.Tokens[i])
				}
				if table.slots[i] != want.Slots[i] {
					t.Errorf("slots[%d] = %d, want %d", i, table.slots[i], want.Slots[i])
				}
			}
			if table.moduloSafe != want.ModuloSafe {
				t.Errorf("moduloSafe = %v, want %v", table.moduloSafe, want.ModuloSafe)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Behavioral coverage ported from test_fqdn_slots.py.
// ---------------------------------------------------------------------------

func TestSlotIsCrc16MaskedTo14Bits(t *testing.T) {
	if got, want := Slot([]byte("123456789")), 0x31C3&0x3FFF; got != want {
		t.Errorf("Slot(%q) = %d, want %d", "123456789", got, want)
	}
}

func TestSlotStaysWithin14Bits(t *testing.T) {
	for _, data := range []string{"", "a", "foo", "{user:123}", "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"} {
		s := Slot([]byte(data))
		if s < 0 || s >= NumSlots {
			t.Errorf("Slot(%q) = %d, out of [0, %d)", data, s, NumSlots)
		}
	}
}

func TestKeySlotHashesOnlyTheHashTagContent(t *testing.T) {
	if got, want := KeySlot("{user:123}:profile"), Slot([]byte("user:123")); got != want {
		t.Errorf("KeySlot(%q) = %d, want %d", "{user:123}:profile", got, want)
	}
	if got, want := KeySlot("prefix:{user:123}:suffix"), Slot([]byte("user:123")); got != want {
		t.Errorf("KeySlot(%q) = %d, want %d", "prefix:{user:123}:suffix", got, want)
	}
}

func TestKeySlotFallsBackWithoutATag(t *testing.T) {
	if got, want := KeySlot("plain:key"), Slot([]byte("plain:key")); got != want {
		t.Errorf("KeySlot(%q) = %d, want %d", "plain:key", got, want)
	}
}

func TestKeySlotFallsBackOnAnEmptyHashTag(t *testing.T) {
	if got, want := KeySlot("{}:rest"), Slot([]byte("{}:rest")); got != want {
		t.Errorf("KeySlot(%q) = %d, want %d", "{}:rest", got, want)
	}
}

func TestKeySlotFallsBackWhenClosingBraceIsMissing(t *testing.T) {
	if got, want := KeySlot("{unterminated"), Slot([]byte("{unterminated")); got != want {
		t.Errorf("KeySlot(%q) = %d, want %d", "{unterminated", got, want)
	}
}

func TestBucketTableTokensLandInTheirOwnSlotRange(t *testing.T) {
	for _, numBuckets := range []int{1, 2, 7, 8, 12, 16, 37, 64, 128, 129, 192} {
		table, err := ComputeBucketTable(numBuckets)
		if err != nil {
			t.Fatalf("ComputeBucketTable(%d): %v", numBuckets, err)
		}
		seen := make(map[string]bool, numBuckets)
		for i, token := range table.tokens {
			if seen[token] {
				t.Errorf("numBuckets=%d: token %q at bucket %d is a duplicate", numBuckets, token, i)
			}
			seen[token] = true

			lo, hi := SlotRange(i, numBuckets)
			s := Slot([]byte(token))
			if s != table.slots[i] {
				t.Errorf("numBuckets=%d: Slot(tokens[%d]) = %d, want stored slot %d", numBuckets, i, s, table.slots[i])
			}
			if s < lo || s >= hi {
				t.Errorf("numBuckets=%d: bucket %d's slot %d outside its range [%d, %d)", numBuckets, i, s, lo, hi)
			}
		}
	}
}

func TestBucketTableIsModuloSafeUpTo129AndNotAbove(t *testing.T) {
	table129, err := ComputeBucketTable(129)
	if err != nil {
		t.Fatalf("ComputeBucketTable(129): %v", err)
	}
	if !table129.moduloSafe {
		t.Error("ComputeBucketTable(129).moduloSafe = false, want true")
	}
	table130, err := ComputeBucketTable(130)
	if err != nil {
		t.Fatalf("ComputeBucketTable(130): %v", err)
	}
	if table130.moduloSafe {
		t.Error("ComputeBucketTable(130).moduloSafe = true, want false")
	}
}

func TestModuloSafeTokensSatisfyTheInterleavedPolicy(t *testing.T) {
	for _, numBuckets := range []int{8, 37, 129} {
		table, err := ComputeBucketTable(numBuckets)
		if err != nil {
			t.Fatalf("ComputeBucketTable(%d): %v", numBuckets, err)
		}
		if !table.moduloSafe {
			t.Fatalf("numBuckets=%d: moduloSafe = false, want true", numBuckets)
		}
		for i, s := range table.slots {
			if s%numBuckets != i {
				t.Errorf("numBuckets=%d: slots[%d]=%d, %d %% %d = %d, want %d", numBuckets, i, s, s, numBuckets, s%numBuckets, i)
			}
		}
	}
}

// TestBucketHasModuloMatchNormalizesNegativeGoModulo cross-checks
// bucketHasModuloMatch against an independent brute-force scan of each
// bucket's range, for a numBuckets (130) large enough that bucketIndex-lo is
// negative for most buckets. Go's % keeps the sign of the dividend (unlike
// Python's, which normalizes to non-negative); a missing normalization in
// bucketHasModuloMatch would silently flip results here and change every
// token, so this test does not reuse that function's own arithmetic.
func TestBucketHasModuloMatchNormalizesNegativeGoModulo(t *testing.T) {
	const numBuckets = 130
	for bucketIndex := 0; bucketIndex < numBuckets; bucketIndex++ {
		lo, hi := SlotRange(bucketIndex, numBuckets)
		want := false
		for s := lo; s < hi; s++ {
			if s%numBuckets == bucketIndex {
				want = true
				break
			}
		}
		if got := bucketHasModuloMatch(lo, hi, numBuckets, bucketIndex); got != want {
			t.Errorf("bucket %d (lo=%d hi=%d): bucketHasModuloMatch = %v, want %v", bucketIndex, lo, hi, got, want)
		}
	}
}

func TestComputeBucketTableRejectsOutOfRangeNumBuckets(t *testing.T) {
	for _, bad := range []int{0, -1, 16385} {
		if _, err := ComputeBucketTable(bad); err == nil {
			t.Errorf("ComputeBucketTable(%d) returned nil error, want an error", bad)
		}
	}
}

func TestTokenPanicsOutOfRange(t *testing.T) {
	table, err := ComputeBucketTable(4)
	if err != nil {
		t.Fatalf("ComputeBucketTable(4): %v", err)
	}
	assertPanics(t, func() { table.Token(4) })
	assertPanics(t, func() { table.Token(-1) })
}

func assertPanics(t *testing.T, f func()) {
	t.Helper()
	defer func() {
		if recover() == nil {
			t.Error("expected a panic, got none")
		}
	}()
	f()
}

func TestComputeBucketTableIsMemoized(t *testing.T) {
	a, err := ComputeBucketTable(16)
	if err != nil {
		t.Fatalf("ComputeBucketTable(16): %v", err)
	}
	b, err := ComputeBucketTable(16)
	if err != nil {
		t.Fatalf("ComputeBucketTable(16): %v", err)
	}
	if a != b {
		t.Errorf("ComputeBucketTable(16) returned distinct pointers %p and %p, want identical", a, b)
	}
}

// TestComputeBucketTableConcurrentFirstAccessIsSound hammers ComputeBucketTable
// for a fresh numBuckets from many goroutines at once and checks every caller
// observed the identical pointer -- the property the sync.Map+sync.Once memo
// exists to guarantee. Run with -race to prove it.
func TestComputeBucketTableConcurrentFirstAccessIsSound(t *testing.T) {
	const numBuckets = 47 // not used by any other test, so this is genuinely a first access
	const goroutines = 64

	var wg sync.WaitGroup
	results := make([]*BucketTable, goroutines)
	errs := make([]error, goroutines)
	wg.Add(goroutines)
	for i := 0; i < goroutines; i++ {
		go func(i int) {
			defer wg.Done()
			results[i], errs[i] = ComputeBucketTable(numBuckets)
		}(i)
	}
	wg.Wait()

	for i, err := range errs {
		if err != nil {
			t.Fatalf("goroutine %d: ComputeBucketTable(%d): %v", i, numBuckets, err)
		}
	}
	first := results[0]
	for i, table := range results {
		if table != first {
			t.Errorf("goroutine %d got pointer %p, want %p (identical to goroutine 0)", i, table, first)
		}
	}
}
