// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/router.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchMode int32

const (
	MatchMode_SINGLE_LEVEL MatchMode = 0 // RFC 6125: a wildcard substitutes exactly one label
	MatchMode_MULTI_LEVEL  MatchMode = 1 // a wildcard matches any descendant depth
)

// Enum value maps for MatchMode.
var (
	MatchMode_name = map[int32]string{
		0: "SINGLE_LEVEL",
		1: "MULTI_LEVEL",
	}
	MatchMode_value = map[string]int32{
		"SINGLE_LEVEL": 0,
		"MULTI_LEVEL":  1,
	}
)

func (x MatchMode) Enum() *MatchMode {
	p := new(MatchMode)
	*p = x
	return p
}

func (x MatchMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_router_proto_enumTypes[0].Descriptor()
}

func (MatchMode) Type() protoreflect.EnumType {
	return &file_proto_router_proto_enumTypes[0]
}

func (x MatchMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchMode.Descriptor instead.
func (MatchMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{0}
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fqdn1         string                 `protobuf:"bytes,1,opt,name=fqdn1,proto3" json:"fqdn1,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Fqdn2         string                 `protobuf:"bytes,3,opt,name=fqdn2,proto3" json:"fqdn2,omitempty"`
	Mode          MatchMode              `protobuf:"varint,4,opt,name=mode,proto3,enum=router.MatchMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_proto_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetFqdn1() string {
	if x != nil {
		return x.Fqdn1
	}
	return ""
}

func (x *LookupRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LookupRequest) GetFqdn2() string {
	if x != nil {
		return x.Fqdn2
	}
	return ""
}

func (x *LookupRequest) GetMode() MatchMode {
	if x != nil {
		return x.Mode
	}
	return MatchMode_SINGLE_LEVEL
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Fqdn1Pattern  string                 `protobuf:"bytes,3,opt,name=fqdn1_pattern,json=fqdn1Pattern,proto3" json:"fqdn1_pattern,omitempty"`
	Fqdn2Pattern  string                 `protobuf:"bytes,4,opt,name=fqdn2_pattern,json=fqdn2Pattern,proto3" json:"fqdn2_pattern,omitempty"`
	Rank1         int32                  `protobuf:"varint,5,opt,name=rank1,proto3" json:"rank1,omitempty"` // lower is more specific
	Rank2         int32                  `protobuf:"varint,6,opt,name=rank2,proto3" json:"rank2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_proto_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_proto_router_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *LookupResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *LookupResponse) GetFqdn1Pattern() string {
	if x != nil {
		return x.Fqdn1Pattern
	}
	return ""
}

func (x *LookupResponse) GetFqdn2Pattern() string {
	if x != nil {
		return x.Fqdn2Pattern
	}
	return ""
}

func (x *LookupResponse) GetRank1() int32 {
	if x != nil {
		return x.Rank1
	}
	return 0
}

func (x *LookupResponse) GetRank2() int32 {
	if x != nil {
		return x.Rank2
	}
	return 0
}

var File_proto_router_proto protoreflect.FileDescriptor

const file_proto_router_proto_rawDesc = "" +
	"\n" +
	"\x12proto/router.proto\x12\x06router\"v\n" +
	"\rLookupRequest\x12\x14\n" +
	"\x05fqdn1\x18\x01 \x01(\tR\x05fqdn1\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x14\n" +
	"\x05fqdn2\x18\x03 \x01(\tR\x05fqdn2\x12%\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x11.router.MatchModeR\x04mode\"\xb1\x01\n" +
	"\x0eLookupResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12#\n" +
	"\rfqdn1_pattern\x18\x03 \x01(\tR\ffqdn1Pattern\x12#\n" +
	"\rfqdn2_pattern\x18\x04 \x01(\tR\ffqdn2Pattern\x12\x14\n" +
	"\x05rank1\x18\x05 \x01(\x05R\x05rank1\x12\x14\n" +
	"\x05rank2\x18\x06 \x01(\x05R\x05rank2*.\n" +
	"\tMatchMode\x12\x10\n" +
	"\fSINGLE_LEVEL\x10\x00\x12\x0f\n" +
	"\vMULTI_LEVEL\x10\x012A\n" +
	"\x06Router\x127\n" +
	"\x06Lookup\x12\x15.router.LookupRequest\x1a\x16.router.LookupResponseB\x15Z\x13routerservice/protob\x06proto3"

var (
	file_proto_router_proto_rawDescOnce sync.Once
	file_proto_router_proto_rawDescData []byte
)

func file_proto_router_proto_rawDescGZIP() []byte {
	file_proto_router_proto_rawDescOnce.Do(func() {
		file_proto_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_router_proto_rawDesc), len(file_proto_router_proto_rawDesc)))
	})
	return file_proto_router_proto_rawDescData
}

var file_proto_router_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_router_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_router_proto_goTypes = []any{
	(MatchMode)(0),         // 0: router.MatchMode
	(*LookupRequest)(nil),  // 1: router.LookupRequest
	(*LookupResponse)(nil), // 2: router.LookupResponse
}
var file_proto_router_proto_depIdxs = []int32{
	0, // 0: router.LookupRequest.mode:type_name -> router.MatchMode
	1, // 1: router.Router.Lookup:input_type -> router.LookupRequest
	2, // 2: router.Router.Lookup:output_type -> router.LookupResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_router_proto_init() }
func file_proto_router_proto_init() {
	if File_proto_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_router_proto_rawDesc), len(file_proto_router_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_router_proto_goTypes,
		DependencyIndexes: file_proto_router_proto_depIdxs,
		EnumInfos:         file_proto_router_proto_enumTypes,
		MessageInfos:      file_proto_router_proto_msgTypes,
	}.Build()
	File_proto_router_proto = out.File
	file_proto_router_proto_goTypes = nil
	file_proto_router_proto_depIdxs = nil
}
